### PR TITLE
Add tour dates and clean up with shortcodes

### PR DESCRIPTION
**Pull request by TheBiggerGuy**
Add Songkick tour dates to the home page and clean up Bandcamp and
Songkick embed codes by using shortcodes.

Fixes Issue #6

### CODE REVIEW

**Comment by padrigali** [comment]
Checking this, the songkick embedded thing looks grand on chrome, but on firefox, the div containing songkick stuff mostly sits behind the "New EP" section and ep cover etc. didn't have time to look into why just now.

**Comment by TheBiggerGuy** [comment]
I cant reproduce the issue. See the zip of the screenshots that I've got. 
[615bdb0659cff6cc094ba9239d8690ea49e96309.zip](https://github.com/TheBiggerGuy/com.tenementjazzband.www/files/2936557/615bdb0659cff6cc094ba9239d8690ea49e96309.zip)

You can use https://www.browserstack.com/screenshots as a good way to test browsers quickly.

**Comment by padrigali** [comment]
Here is my screenshot of site on firefox 65.0.1 running on KDE Neon. Probably not the average visitor's setup and it looks to be fine for all the other browser bits you sent through, yes. Probably good to get this change pushed then, yes.

I'll check out browserstack for sure

image

**Comment by padrigali** [comment]
Ok, so disabling my [HTTPS Everywhere](https://www.eff.org/https-everywhere) add-on allows it to function as expected.

**Pull request merged**
